// Auto-generated by generateKeystaticData.ts - DO NOT EDIT MANUALLY
// Run 'npm run generate:keystatic-data' to regenerate

export const categoryOptions = [
  {
    "label": "Artificial Intelligence",
    "value": "artificial-intelligence"
  },
  {
    "label": "Cellular Automata",
    "value": "cellular-automata"
  },
  {
    "label": "Fuzzy Logic",
    "value": "fuzzy-logic"
  },
  {
    "label": "Gamedev",
    "value": "gamedev"
  },
  {
    "label": "Graphics",
    "value": "graphics"
  },
  {
    "label": "Machine Learning",
    "value": "machine-learning"
  },
  {
    "label": "Procedural Generation",
    "value": "procedural-generation"
  },
  {
    "label": "Roguelike",
    "value": "roguelike"
  }
];
