// Auto-generated by generateKeystaticData.ts - DO NOT EDIT MANUALLY
// Run 'npm run generate:keystatic-data' to regenerate

export const tags = [
  "algorithms",
  "berlin-interpretation",
  "c-sharp",
  "domain-specific-language",
  "experiment-1",
  "function-approximation",
  "game-ai",
  "game-engine",
  "image-processing",
  "large-language-model",
  "maze-generation",
  "musings",
  "npc-behavior",
  "pacman-like",
  "pixel-art",
  "policy-based-learning",
  "python",
  "reinforcement-learning",
  "rust",
  "sekrit-project-1",
  "terrain-generation",
  "world-building"
];
