#!/usr/bin/env node
/**
 * Generates static category and tag files for Keystatic configuration
 * Run this during build to update src/scripts/onbuild/categories.ts and tags.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Simple frontmatter parser
function parseFrontmatter(content: string): any {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) return {};

  const frontmatter = frontmatterMatch[1];
  const data: any = {};

  // Parse categories (array format: categories: [foo, bar] or space-separated: categories: foo bar)
  const categoriesMatch = frontmatter.match(/^categories:\s*\[(.*?)\]/m);
  if (categoriesMatch) {
    data.categories = categoriesMatch[1].split(',').map(s => s.trim());
  } else {
    const categoriesLineMatch = frontmatter.match(/^categories:\s*(.+)$/m);
    if (categoriesLineMatch) {
      data.categories = categoriesLineMatch[1].trim().split(/\s+/);
    }
  }

  // Parse tags (array format: tags: [foo, bar] or space-separated: tags: foo bar)
  const tagsMatch = frontmatter.match(/^tags:\s*\[(.*?)\]/m);
  if (tagsMatch) {
    data.tags = tagsMatch[1].split(',').map(s => s.trim());
  } else {
    const tagsLineMatch = frontmatter.match(/^tags:\s*(.+)$/m);
    if (tagsLineMatch) {
      data.tags = tagsLineMatch[1].trim().split(/\s+/);
    }
  }

  return data;
}

// Read all post files from the posts directory
function getAllPostFiles(dir: string): string[] {
  const files: string[] = [];
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      // Skip _drafts directories
      if (item === '_drafts') continue;
      files.push(...getAllPostFiles(fullPath));
    } else if (item.endsWith('.md') || item.endsWith('.mdx')) {
      files.push(fullPath);
    }
  }

  return files;
}

// Extract categories and tags from frontmatter
function extractKeys(postFiles: string[]): { categories: Set<string>, tags: Set<string> } {
  const categories = new Set<string>();
  const tags = new Set<string>();

  for (const file of postFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const data = parseFrontmatter(content);

    // Extract categories
    if (data.categories) {
      const cats = Array.isArray(data.categories)
        ? data.categories
        : [data.categories];
      cats.forEach((cat: string) => categories.add(cat.toLowerCase()));
    }

    // Extract tags
    if (data.tags) {
      const tagList = Array.isArray(data.tags)
        ? data.tags
        : [data.tags];
      tagList.forEach((tag: string) => tags.add(tag.toLowerCase()));
    }
  }

  return { categories, tags };
}

// Main execution
const postsDir = path.join(__dirname, '../assets/posts/hiivelabs.com');
const postFiles = getAllPostFiles(postsDir);
const { categories, tags } = extractKeys(postFiles);

// Transform categories into Keystatic option format
const categoryOptions = Array.from(categories).map(cat => ({
  label: cat.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
  value: cat,
})).sort((a, b) => a.label.localeCompare(b.label));

// Transform tags into simple array (sorted)
const tagList = Array.from(tags).sort();

// Generate categories.ts content
const categoriesContent = `// Auto-generated by generateKeystaticData.ts - DO NOT EDIT MANUALLY
// Run 'npm run generate:keystatic-data' to regenerate

export const categoryOptions = ${JSON.stringify(categoryOptions, null, 2)};
`;

// Generate tags.ts content
const tagsContent = `// Auto-generated by generateKeystaticData.ts - DO NOT EDIT MANUALLY
// Run 'npm run generate:keystatic-data' to regenerate

export const tags = ${JSON.stringify(tagList, null, 2)};
`;

// Ensure onbuild directory exists
const onbuildDir = path.join(__dirname, 'onbuild');
if (!fs.existsSync(onbuildDir)) {
  fs.mkdirSync(onbuildDir, { recursive: true });
}

// Write files
fs.writeFileSync(path.join(onbuildDir, 'categories.ts'), categoriesContent);
fs.writeFileSync(path.join(onbuildDir, 'tags.ts'), tagsContent);

console.log('✅ Generated categories.ts and tags.ts');
console.log(`   Categories: ${categoryOptions.length}`);
console.log(`   Tags: ${tagList.length}`);
