name: Manage Posts and Drafts

on:
  #  push:
  #    branches:
  #      - main  # Change this to your default branch if different
  # schedule:
  # - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering with inputs
env:
  # Setting environment variables with the value of a configuration variable
  ROOT_URL: ${{ vars.ROOT_URL }}
  ANNOUNCE_START_DATE: ${{ vars.ANNOUNCE_START_DATE }}
  SITE_CODE: ${{ vars.SITE_CODE }}
jobs:
  manage_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Required Python Packages
        run: |
          pip install -r requirements.txt

      - name: Run Python Script to Manage Posts and Drafts
        run: |
          python manage_posts.py

      - name: Post to Bluesky
        if: always()
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          python post_to_bluesky.py \
            --root-url "${{ env.ROOT_URL }}" \
            --announce-start-date "${{ env.ANNOUNCE_START_DATE }}"

      - name: Commit and Push Changes
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # Stage all changes
          git add -A

          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated post and draft management [skip ci]"
            git push
          fi
